#!/usr/bin/env python3
import sys
import re

# Regular expression to match ANSI escape sequences
ANSI_ESCAPE = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

def strip_ansi(text):
    return ANSI_ESCAPE.sub('', text)

def main():
    for line in sys.stdin:
        print(strip_ansi(line), end='')

if __name__ == "__main__":
    main()
